"""Generate additional screenshots for the new features."""
from PIL import Image, ImageDraw, ImageFont
import os

try:
    font = ImageFont.truetype("C:/Windows/Fonts/consola.ttf", 15)
    font_sm = ImageFont.truetype("C:/Windows/Fonts/consola.ttf", 12)
    font_title = ImageFont.truetype("C:/Windows/Fonts/consola.ttf", 18)
except:
    font = ImageFont.load_default()
    font_sm = font
    font_title = font

BG = (22, 27, 34)
BAR_BG = (33, 38, 45)
BORDER = (48, 54, 61)
WHITE = (230, 237, 243)
GREEN = (63, 185, 80)
RED = (248, 81, 73)
DIM = (139, 148, 158)
BLUE = (121, 192, 255)
YELLOW = (210, 153, 34)
PURPLE = (203, 166, 247)

OUT = os.path.dirname(os.path.abspath(__file__))


def draw_bar(draw, w):
    draw.rectangle([0, 0, w, 40], fill=BAR_BG)
    draw.ellipse([16, 13, 28, 25], fill=(255, 95, 87))
    draw.ellipse([34, 13, 46, 25], fill=(254, 188, 46))
    draw.ellipse([52, 13, 64, 25], fill=(40, 200, 64))
    draw.line([0, 40, w, 40], fill=BORDER)


def screenshot_compliance():
    w, h = 950, 700
    img = Image.new("RGB", (w, h), BG)
    draw = ImageDraw.Draw(img)
    draw_bar(draw, w)
    draw.text((76, 12), "Compliance Incident Report", fill=DIM, font=font)

    x, y = 24, 56
    lines = [
        ("  VYAAPTI COMPLIANCE INCIDENT REPORT", BLUE, font_title),
        ("  Auto-generated by Test-Triage Copilot (IBM Bob 2.0)", DIM, font_sm),
        ("", DIM, font),
        ("  Report ID : VYP-IR-20260926-012608", WHITE, font),
        ("  Severity  : CRITICAL", RED, font),
        ("  Status    : OPEN - Requires Immediate Remediation", RED, font),
        ("", DIM, font),
        ("  INCIDENT 1: Structuring Detection Disabled", YELLOW, font),
        ("  Regulation : RBI Master Direction on KYC, Section 29", DIM, font_sm),
        ("  State      : BROKEN", RED, font_sm),
        ("  Impact     : Rs 50L RBI threshold NOT enforced", WHITE, font_sm),
        ("  Penalty    : Up to Rs 10L per unreported transaction", RED, font_sm),
        ("  Fix        : 49_50_000 -> self.STRUCTURING_UPPER_BOUND", GREEN, font_sm),
        ("  Priority   : P0 - IMMEDIATE", RED, font_sm),
        ("", DIM, font),
        ("  INCIDENT 2: Velocity Monitoring Disabled", YELLOW, font),
        ("  Regulation : PMLA, 2002", DIM, font_sm),
        ("  State      : BROKEN", RED, font_sm),
        ("  Impact     : All velocity calculations 60x too low", WHITE, font_sm),
        ("  Fix        : delta_seconds / 60 -> / 3600", GREEN, font_sm),
        ("  Priority   : P0 - IMMEDIATE", RED, font_sm),
        ("", DIM, font),
        ("  INCIDENT 3: Circular Pattern Detection", BLUE, font),
        ("  State      : BROKEN  |  Priority: P1 - HIGH", YELLOW, font_sm),
        ("", DIM, font),
        ("  REMEDIATION TIMELINE", WHITE, font),
        ("  [ ] Apply 3 code fixes", DIM, font_sm),
        ("  [ ] Notify Compliance Officer", DIM, font_sm),
        ("  [ ] Review last 30 days for missed STRs", DIM, font_sm),
        ("  [ ] Update CI to block on compliance failures", DIM, font_sm),
    ]

    for text, color, f in lines:
        draw.text((x, y), text, fill=color, font=f)
        y += 20 if f != font_title else 26

    img.save(os.path.join(OUT, "screenshot_compliance_report.jpg"), "JPEG", quality=95)
    print("Saved: screenshot_compliance_report.jpg")


def screenshot_edge_tests():
    w, h = 950, 400
    img = Image.new("RGB", (w, h), BG)
    draw = ImageDraw.Draw(img)
    draw_bar(draw, w)
    draw.text((76, 12), "Auto-Generated Edge Cases", fill=DIM, font=font)

    x, y = 24, 56
    draw.text((x, y), "Bob 2.0: Auto-Generated Edge-Case Tests", fill=BLUE, font=font)
    y += 28
    draw.text((x, y), "New tests written to prevent future regressions:", fill=DIM, font=font_sm)
    y += 24

    tests = [
        ("test_time_compression_exact_boundary", "60 min = strict < check", GREEN),
        ("test_structuring_lower_edge", "Rs 49L lower band boundary", GREEN),
        ("test_structuring_upper_edge", "Rs 51L upper band boundary", GREEN),
        ("test_structuring_outside_band", "Rs 55L must NOT trigger", GREEN),
        ("test_non_circular_chain", "A->B->C->D negative test", GREEN),
        ("test_velocity_exactly_at_threshold", "Rs 1Cr/hr strict > check", GREEN),
        ("test_maximum_risk_all_factors", "All 5 factors = score 100", GREEN),
    ]

    for name, desc, color in tests:
        draw.text((x, y), "  [NEW]", fill=PURPLE, font=font)
        draw.text((x + 80, y), name, fill=color, font=font)
        draw.text((x + 480, y), desc, fill=DIM, font=font_sm)
        y += 22

    y += 16
    draw.text((x, y), "7 new tests generated | All boundary/negative cases covered", fill=GREEN, font=font_sm)
    y += 20
    draw.text((x, y), "Codebase strengthened beyond its original state", fill=BLUE, font=font_sm)

    img.save(os.path.join(OUT, "screenshot_new_tests.jpg"), "JPEG", quality=95)
    print("Saved: screenshot_new_tests.jpg")


def screenshot_ci_rules():
    w, h = 950, 380
    img = Image.new("RGB", (w, h), BG)
    draw = ImageDraw.Draw(img)
    draw_bar(draw, w)
    draw.text((76, 12), "CI/CD Prevention Rules", fill=DIM, font=font)

    x, y = 24, 56
    draw.text((x, y), "Bob 2.0: Regression Prevention Rules", fill=BLUE, font=font)
    y += 32

    rules = [
        ("Rule 1", "Block deployment on compliance test failures", "@pytest.mark.compliance", RED),
        ("Rule 2", "Unit conversion assertions in shared helpers", "assert hours < 8760", YELLOW),
        ("Rule 3", "No hardcoded thresholds in check_* methods", "pre-commit hook scan", YELLOW),
        ("Rule 4", "Mandatory review for scoring changes", "CODEOWNERS: @compliance-team", PURPLE),
        ("Rule 5", "Auto-triage on every PR touching scoring", "CI: triage-copilot-check", BLUE),
    ]

    for label, desc, detail, color in rules:
        draw.rectangle([x, y-2, x+70, y+18], fill=(color[0]//6, color[1]//6, color[2]//6), outline=color)
        draw.text((x+6, y), label, fill=color, font=font_sm)
        draw.text((x+84, y), desc, fill=WHITE, font=font)
        draw.text((x+84, y+20), detail, fill=DIM, font=font_sm)
        y += 48

    y += 8
    draw.text((x, y), "5 CI rules auto-generated | Zero future regressions", fill=GREEN, font=font_sm)

    img.save(os.path.join(OUT, "screenshot_ci_rules.jpg"), "JPEG", quality=95)
    print("Saved: screenshot_ci_rules.jpg")


if __name__ == "__main__":
    screenshot_compliance()
    screenshot_edge_tests()
    screenshot_ci_rules()
    print("\nAll 3 additional screenshots saved!")
