"""
AUTO-GENERATED EDGE-CASE TESTS
===============================
Generated by Vyaapti Test-Triage Copilot (IBM Bob 2.0)

After fixing the 3 bugs, Bob also generates NEW test cases to prevent
future regressions -- strengthening the test suite beyond its original state.
"""

from datetime import datetime, timedelta
from chain_scoring import Transaction, RiskChainAnalyzer


def _make_chain(accounts, amount, start, interval_min):
    return [
        Transaction(accounts[i], accounts[i+1], amount,
                    start + timedelta(minutes=interval_min * i))
        for i in range(len(accounts) - 1)
    ]


# =====================================================================
# NEW TEST 1: Time span boundary -- exactly 1 hour should NOT trigger
# =====================================================================
def test_time_compression_exact_boundary():
    """Chain spanning exactly 60 minutes should NOT trigger time compression.
    
    Regression guard: ensures the < comparison is strict, not <=.
    Previously, the /60 bug made this untestable.
    """
    a = RiskChainAnalyzer()
    s = datetime(2024, 1, 1, 10, 0)
    chain = [
        Transaction("A", "B", 10_00_000, s),
        Transaction("B", "C", 10_00_000, s + timedelta(minutes=60)),
    ]
    result = a.check_time_compression(chain)
    assert result is False, \
        "Exactly 60 min = 1 hour should NOT trigger time compression (strict <)"


# =====================================================================
# NEW TEST 2: Structuring -- both edges of the band
# =====================================================================
def test_structuring_lower_edge():
    """Average exactly at Rs 49L (lower edge) should trigger structuring."""
    a = RiskChainAnalyzer()
    s = datetime(2024, 1, 1, 10, 0)
    chain = [
        Transaction("A", "B", 49_00_000, s),
        Transaction("B", "C", 49_00_000, s + timedelta(hours=1)),
    ]
    assert a.check_structuring(chain) is True, \
        "Rs 49L is the lower edge of the band -- must trigger"


def test_structuring_upper_edge():
    """Average exactly at Rs 51L (upper edge) should trigger structuring."""
    a = RiskChainAnalyzer()
    s = datetime(2024, 1, 1, 10, 0)
    chain = [
        Transaction("A", "B", 51_00_000, s),
        Transaction("B", "C", 51_00_000, s + timedelta(hours=1)),
    ]
    assert a.check_structuring(chain) is True, \
        "Rs 51L is the upper edge of the band -- must trigger"


def test_structuring_outside_band():
    """Average at Rs 55L (above band) should NOT trigger structuring."""
    a = RiskChainAnalyzer()
    s = datetime(2024, 1, 1, 10, 0)
    chain = [
        Transaction("A", "B", 55_00_000, s),
        Transaction("B", "C", 55_00_000, s + timedelta(hours=1)),
    ]
    assert a.check_structuring(chain) is False, \
        "Rs 55L is outside the Rs 49L-51L band -- must NOT trigger"


# =====================================================================
# NEW TEST 3: Circular pattern -- non-circular should NOT trigger
# =====================================================================
def test_non_circular_chain():
    """A->B->C->D (not circular) should NOT trigger circular pattern."""
    a = RiskChainAnalyzer()
    s = datetime(2024, 1, 1, 10, 0)
    chain = [
        Transaction("ACC_001", "ACC_002", 10_00_000, s),
        Transaction("ACC_002", "ACC_003", 10_00_000, s + timedelta(hours=1)),
        Transaction("ACC_003", "ACC_004", 10_00_000, s + timedelta(hours=2)),
    ]
    assert a.check_circular_pattern(chain) is False, \
        "A->B->C->D is not circular -- sender-to-receiver check must not false-positive"


# =====================================================================
# NEW TEST 4: Velocity at exactly the threshold
# =====================================================================
def test_velocity_exactly_at_threshold():
    """Velocity exactly Rs 1Cr/hr should NOT trigger (must exceed, not equal)."""
    a = RiskChainAnalyzer()
    s = datetime(2024, 1, 1, 10, 0)
    # Rs 1Cr in exactly 1 hour = Rs 1Cr/hr (not > threshold)
    chain = [
        Transaction("A", "B", 50_00_000, s),
        Transaction("B", "C", 50_00_000, s + timedelta(hours=1)),
    ]
    assert a.check_rapid_succession(chain) is False, \
        "Exactly Rs 1Cr/hr should NOT trigger (threshold is strict >)"


# =====================================================================
# NEW TEST 5: Full risk score -- all 5 factors triggered simultaneously
# =====================================================================
def test_maximum_risk_all_factors():
    """Chain that triggers ALL 5 risk factors should score 100 (capped)."""
    a = RiskChainAnalyzer()
    s = datetime(2024, 1, 1, 10, 0)
    # Circular: ACC_001 -> ... -> ACC_001
    # 5+ hops: 6 transactions
    # Fast: all within 30 minutes
    # High velocity: Rs 50L * 6 = Rs 3Cr in 0.5hr = Rs 6Cr/hr
    # Structuring: avg Rs 50L (in the band)
    chain = [
        Transaction("ACC_001", "ACC_002", 50_00_000, s),
        Transaction("ACC_002", "ACC_003", 50_00_000, s + timedelta(minutes=5)),
        Transaction("ACC_003", "ACC_004", 50_00_000, s + timedelta(minutes=10)),
        Transaction("ACC_004", "ACC_005", 50_00_000, s + timedelta(minutes=15)),
        Transaction("ACC_005", "ACC_006", 50_00_000, s + timedelta(minutes=20)),
        Transaction("ACC_006", "ACC_001", 50_00_000, s + timedelta(minutes=25)),
    ]
    result = a.calculate_risk_score(chain)
    assert result["total_score"] == 100, \
        "All 5 factors should fire: 30+25+20+15+10=100; got %d" % result["total_score"]
    assert result["risk_level"] == "CRITICAL"
    assert len(result["factors"]) == 5, \
        "Expected 5 factors, got %d: %s" % (len(result["factors"]), result["factors"])


# =====================================================================
# Runner
# =====================================================================

ALL_NEW_TESTS = [
    test_time_compression_exact_boundary,
    test_structuring_lower_edge,
    test_structuring_upper_edge,
    test_structuring_outside_band,
    test_non_circular_chain,
    test_velocity_exactly_at_threshold,
    test_maximum_risk_all_factors,
]

if __name__ == "__main__":
    print("=" * 72)
    print("  Auto-Generated Edge-Case Tests (Bob 2.0)")
    print("=" * 72)
    print()

    passed = 0
    failed = 0
    for fn in ALL_NEW_TESTS:
        name = fn.__name__
        try:
            fn()
            print("  [PASS]  %s" % name)
            passed += 1
        except AssertionError as e:
            print("  [FAIL]  %s" % name)
            print("          -> %s" % e)
            failed += 1
        except Exception as e:
            print("  [ERR]   %s" % name)
            print("          -> %s" % e)
            failed += 1

    print()
    print("-" * 72)
    print("  NEW TESTS: %d  |  PASSED: %d  |  FAILED: %d" % (passed+failed, passed, failed))
    print("-" * 72)
